application/forms.py
from flask_wtf import FlaskForm
from wtforms import DecimalField, StringField, SubmitField, SelectField
from wtforms.validators import InputRequired, Length, NumberRange

from application.models.blockchain.Wallet import get_user_wallet, Wallet, get_main_wallet


class SendForm(FlaskForm):
    """Form for creating a transaction"""
    quantity = DecimalField(
        'Quantity',
        validators=[InputRequired(), NumberRange(min=1)],
        render_kw={"placeholder": "Quantity to Send"},
        default=1
    )
    receiver = SelectField(
        'Receiver',
        coerce=str,
        choices=[get_user_wallet().public_key.encode("utf-8"), get_main_wallet().public_key.encode("utf-8")],
    )
    # choose from the 2 users
    submit = SubmitField('Send')

application/__init__.py
from flask import Flask

from application.models.blockchain.Wallet import generate_new_wallet, Wallet

app = Flask(__name__)
port = 9999
hostname = "127.0.0.1"


def getFlaskContext():
    return app, port, hostname

application/views.py
import json

from flask import Blueprint, render_template
from wtforms import DecimalField

from .forms import SendForm
from .models.blockchain.Blockchain import get_blockchain
from .models.blockchain.Transaction import Coinbase
from .models.blockchain.UTXO import UTXO
from .models.blockchain.Wallet import get_main_wallet, get_user_wallet

main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

# get the balance a public key has
def get_balance_for_public_key(public_key):
    balance = 0
    # iterate all utxos for the public key and sum their value
    for utxo in get_blockchain().get_utxos(public_key):
        assert isinstance(utxo, UTXO)
        if utxo.public_key == public_key:
            balance = balance + utxo.message
    return balance


@main_bp.route('/')
# @login_required
def index():
    """Main page, displays balance"""
    wallet = get_main_wallet()
    balance = get_balance_for_public_key(wallet.public_key)
    return render_template('index.html', balance=balance)


@main_bp.route('/send', methods=['GET', 'POST'])
def send():
    """Provides a form to create and send a transaction"""
    form = SendForm()
    wallet = get_main_wallet()
    # print(get_blockchain().get_utxos(wallet.public_key))
    if form.validate_on_submit():
        # send 1 to user wallet
        wallet.send_money(get_blockchain(), [get_user_wallet().public_key], [1])
    return render_template('send.html', form=form, address=wallet.address)


@main_bp.route('/transactions', methods=['GET', 'POST'])
def transactions():
    """Displays all transactions from the user"""
    wallet = get_main_wallet()
    blocks = get_blockchain().blocks
    received_coinbase_txns = []
    sent_txns = []
    # iterate all blocks and search for txns of the current wallet (main wallet)
    # and search for the coinbase txns the wallet received and the txns it made
    for block in blocks:
        for tx in block.transactions:
            if isinstance(tx, Coinbase):
                for pk in tx.receiver_public_keys:
                    if wallet.public_key == pk:
                        received_coinbase_txns.append(tx)
                continue
            elif tx.utxos[0].public_key is wallet.public_key:
                sent_txns.append(tx)
    txns = set(sent_txns)

    return render_template('transactions.html', txns=txns, cbtxns=received_coinbase_txns)


@main_bp.route('/mnemonic')
# @login_required
def mnemonic():
    """Displays the private key """
    wallet = get_main_wallet()
    return render_template('mnemonic.html', passphrase=wallet.private_key)


@main_bp.route('/last_block')
# @login_required
def get_last_block():
    """Displays the recovery passphrase"""

    return json.dumps(get_blockchain().get_topmost_block().get_dict(), indent=4)

application/templates/index.html
{% extends 'layout.html' %}

{% block content %}
<h1>Crypto Balance</h1>
<h1>{{ balance }}</h1>
<h2><a href="{{ url_for('main_bp.mnemonic') }}">View Private Key</a></h2>
{% endblock %}

application/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="shortcut icon">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/nav.css') }}" rel="stylesheet">
    <title>Wallet</title>
</head>
<body>
{% include 'nav.html' %}
<div class="container">
    <div class="content">
        {% block content %} {% endblock %}
    </div>
</div>
</body>
</html>

application/templates/mnemonic.html
{% extends 'layout.html' %}

{% block content %}
<h1>Your Account Recovery Phrase:</h1>
<br>
<h2>{{ passphrase }}</h2>
<h2>Note this down and keep it secret!</h2>
{% endblock %}

application/templates/nav.html
<nav class="topnav">
    <a href="{{ url_for('main_bp.index') }}" {% if request.path==url_for('main_bp.index') %} class="active" {% endif %}>Balance</a>
    <a href="{{ url_for('main_bp.send') }}" {% if request.path==url_for('main_bp.send') %} class="active" {% endif %}>Send/Receive</a>
    <a href="{{ url_for('main_bp.transactions') }}" {% if request.path==url_for('main_bp.transactions') %}
       class="active" {% endif %}>Transactions</a>
</nav>

application/templates/send.html
{% extends 'layout.html' %}

{% block content %}
<h1>Send Algorand</h1>
<form action="{{ url_for('main_bp.send') }}" method="post">
    {{ form.csrf_token }}

    {{ form.quantity.label }}
    <br>
    {{ form.quantity }}
    <br>
    {% if form.quantity.errors %}
    <h3>{{ form.quantity.errors[0] }}</h3>
    {% endif %}
    <br>
    {{ form.receiver.label }}
    <br>
    {{ form.receiver }}
    <br>
    {% if form.receiver.errors %}
    <h3>{{ form.receiver.errors[0] }}</h3>
    {% endif %}

    <br>
    {{ form.submit }}
</form>
<h1>Receive Algorand</h1>
<h2>Your base64 address is:</h2>
<h4>{{ address }}</h4>
{% endblock %}

application/templates/success.html
{% extends 'layout.html' %}

{% block content %}
{% if success %}
<h1>Transaction Success</h1>
{% else %}
<h1>Transaction Failed</h1>
{% endif %}
{% endblock %}

application/templates/transactions.html
{% extends 'layout.html' %}

{% block content %}
<h1>Transactions</h1>

<table>
    <tr>
        <th>Hash</th>
        <th>Quantity</th>
    </tr>
    {% for txn in txns %}
    <tr>
        <td>{{ txn.get_hash() }}</td>
        <td>{{ txn.messages }}</td>
        </div>
    </tr>
    {% endfor %}
</table>

<h1>Coinbase Transactions - for my mined blocks</h1>

<table>
    <tr>
        <th>Sender/Receiver</th>
        <th>Quantity</th>
    </tr>
    {% for txn in cbtxns %}
    <tr>
        <td>{{ txn.get_hash()}}</td>
        <td>{{ txn.messages }}</td>
        </div>
    </tr>
    {% endfor %}
</table>
{% endblock %}